### ISSUE TITLE
Error in `finish_prediction(prediction, newdata)`

### ISSUE THREAD

**Issue by fabianmoronzirfas** [KWB-R/fhpredict#62]
@hsonne 😭 
I finally managed to rebuild the image, but now I get the error below.

```json
 {
        "data": {},
        "success": [
            false
        ],
        "message": [
            "Error in finish_prediction(prediction, newdata) : \n  ncol(prediction) == nrow(newdata) is not TRUE\n"
        ]
    },
```

**Comment by hsonne** [comment]
Which user, which bathing spot?

**Comment by hsonne** [comment]
There was no data available for prediction. The reason was that all time series were filtered for the summer (bathing) period. I prepared a new release [v0.12.0](https://github.com/KWB-R/fhpredict/releases/tag/v0.12.0) in which

* a more clear error message is given in case of missing data
* the filter for the summer period is removed.

**Comment by fabianmoronzirfas** [comment]
Yiiiiiihaaaaaa!!!!!!

![celeb](https://media2.giphy.com/media/kyLYXonQYYfwYDIeZl/giphy.gif)
```
{
        "data": [
            458
        ],
        "success": [
            true
        ],
        "message": [
            "1 predictions have been posted to the database."
        ]
    },
```
